// <auto-generated />
using System;
using DiplomaWebApp.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiplomaWebApp.Migrations
{
    [DbContext(typeof(MathBattlesDbContext))]
    [Migration("20260310094603_morelinks")]
    partial class morelinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiplomaWebApp.Models.Break", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeclareTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InitiatorTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorTeamId");

                    b.HasIndex("RoundId");

                    b.ToTable("Breaks");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.CaptainsRound", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("Participant1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Participant2Id")
                        .HasColumnType("integer");

                    b.Property<int>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.HasIndex("Participant1Id");

                    b.HasIndex("Participant2Id");

                    b.ToTable("CaptainsRounds");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeclareTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChallengeAccepted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCheckingCorrectness")
                        .HasColumnType("boolean");

                    b.Property<int>("RequestingTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("RequestingTeamId");

                    b.HasIndex("TaskId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Change", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeclareTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitiatorTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("NewParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorTeamId");

                    b.HasIndex("NewParticipantId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoundId");

                    b.ToTable("Changes");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessorId")
                        .HasColumnType("text");

                    b.Property<int>("AssessorPoints")
                        .HasColumnType("integer");

                    b.Property<string>("CaptainsRoundFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ChallengingTeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("GameEnded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolvingTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TaskSolvingStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Team1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Team1Points")
                        .HasColumnType("integer");

                    b.Property<int?>("Team2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Team2Points")
                        .HasColumnType("integer");

                    b.Property<bool>("TeamRejectedToChallenge")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AssessorId");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Jure", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Fatname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Login");

                    b.ToTable("Jures");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Mistake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JureCost")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentsCost")
                        .HasColumnType("integer");

                    b.Property<int>("ResultsId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResultsId");

                    b.ToTable("Mistakes");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.RolesChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FullRoleChange")
                        .HasColumnType("boolean");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId")
                        .IsUnique();

                    b.ToTable("RolesChanges");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<bool>("NoSolution")
                        .HasColumnType("boolean");

                    b.Property<int?>("OpponentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.HasIndex("OpponentId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.RoundResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correctness")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RoundEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<int>("Team1Points")
                        .HasColumnType("integer");

                    b.Property<int>("Team2Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId")
                        .IsUnique();

                    b.ToTable("RoundResults");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fatname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaptainId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ViceCaptainId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.HasIndex("ViceCaptainId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GameProblem", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("integer");

                    b.Property<int>("TasksId")
                        .HasColumnType("integer");

                    b.HasKey("GamesId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("GameProblem");
                });

            modelBuilder.Entity("StudentTeam", b =>
                {
                    b.Property<int>("StudentsId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamsId")
                        .HasColumnType("integer");

                    b.HasKey("StudentsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("StudentTeam");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Break", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Team", "InitiatorTeam")
                        .WithMany("Breaks")
                        .HasForeignKey("InitiatorTeamId");

                    b.HasOne("DiplomaWebApp.Models.Round", "Round")
                        .WithMany("Breaks")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitiatorTeam");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.CaptainsRound", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Game", "Game")
                        .WithOne("CaptainsRound")
                        .HasForeignKey("DiplomaWebApp.Models.CaptainsRound", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Student", "Participant1")
                        .WithMany()
                        .HasForeignKey("Participant1Id");

                    b.HasOne("DiplomaWebApp.Models.Student", "Participant2")
                        .WithMany()
                        .HasForeignKey("Participant2Id");

                    b.Navigation("Game");

                    b.Navigation("Participant1");

                    b.Navigation("Participant2");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Challenge", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Game", "Game")
                        .WithMany("Challenges")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Team", "RequestingTeam")
                        .WithMany("Challenges")
                        .HasForeignKey("RequestingTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Problem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("RequestingTeam");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Change", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Team", "InitiatorTeam")
                        .WithMany("Changes")
                        .HasForeignKey("InitiatorTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Student", "NewParticipant")
                        .WithMany()
                        .HasForeignKey("NewParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Role", "Role")
                        .WithMany("Changes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Round", "Round")
                        .WithMany("Changes")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitiatorTeam");

                    b.Navigation("NewParticipant");

                    b.Navigation("Role");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Game", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Jure", "Assessor")
                        .WithMany()
                        .HasForeignKey("AssessorId");

                    b.HasOne("DiplomaWebApp.Models.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id");

                    b.HasOne("DiplomaWebApp.Models.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id");

                    b.Navigation("Assessor");

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Mistake", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.RoundResults", "Results")
                        .WithMany("Mistakes")
                        .HasForeignKey("ResultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Results");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.RolesChange", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Round", "Round")
                        .WithOne("RolesChange")
                        .HasForeignKey("DiplomaWebApp.Models.RolesChange", "RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Round", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Challenge", "Challenge")
                        .WithOne("Round")
                        .HasForeignKey("DiplomaWebApp.Models.Round", "ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Student", "Opponent")
                        .WithMany("OpponentRounds")
                        .HasForeignKey("OpponentId");

                    b.HasOne("DiplomaWebApp.Models.Problem", null)
                        .WithMany("Rounds")
                        .HasForeignKey("ProblemId");

                    b.HasOne("DiplomaWebApp.Models.Student", "Speaker")
                        .WithMany("SpeakerRounds")
                        .HasForeignKey("SpeakerId");

                    b.Navigation("Challenge");

                    b.Navigation("Opponent");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.RoundResults", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Round", "Round")
                        .WithOne("RoundResults")
                        .HasForeignKey("DiplomaWebApp.Models.RoundResults", "RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Team", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Student", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainId");

                    b.HasOne("DiplomaWebApp.Models.Student", "ViceCaptain")
                        .WithMany()
                        .HasForeignKey("ViceCaptainId");

                    b.Navigation("Captain");

                    b.Navigation("ViceCaptain");
                });

            modelBuilder.Entity("GameProblem", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Problem", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentTeam", b =>
                {
                    b.HasOne("DiplomaWebApp.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaWebApp.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Challenge", b =>
                {
                    b.Navigation("Round")
                        .IsRequired();
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Game", b =>
                {
                    b.Navigation("CaptainsRound")
                        .IsRequired();

                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Problem", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Role", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Round", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("Changes");

                    b.Navigation("RolesChange");

                    b.Navigation("RoundResults");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.RoundResults", b =>
                {
                    b.Navigation("Mistakes");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Student", b =>
                {
                    b.Navigation("OpponentRounds");

                    b.Navigation("SpeakerRounds");
                });

            modelBuilder.Entity("DiplomaWebApp.Models.Team", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("Challenges");

                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
